# Generated by Django 4.2 on 2025-08-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заимствования')),
                ('return_date', models.DateTimeField(verbose_name='Дата возврата')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowings', to='settings.book')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowings', to='settings.reader')),
            ],
            options={
                'verbose_name': 'Заимствование',
                'verbose_name_plural': 'Заимствования',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
