# Generated by Django 4.2 on 2025-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
